- package.json
- typings.d.ts
---
---
Importing this module as a dependency into `js-client-sdk` was failing. I found that a recent change (https://github.com/Eppo-exp/js-client-sdk-common/commit/4fdcce52bfcc83a765785b6bd0444acd8d787a74) from using a combination of npm & yarn to just yarn led to the primary typings file not longer being compiled into the `dist` directory:
```
➜  js-client-sdk-common git:(heads/tags/v1.2.2) ✗ yarn
➜  js-client-sdk-common git:(heads/tags/v1.2.2) ✗ ls -la dist/js-client-sdk-common.d.ts
-rw-r--r--  1 leo  staff  6901 Aug 30 11:22 dist/js-client-sdk-common.d.ts
➜  js-client-sdk-common git:(main) yarn
➜  js-client-sdk-common …
```
> add typings and module declaration (FF-863)

- Makefile
- package.json
- src/assignment-hooks.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/dto/experiment-configuration-dto.ts
- src/dto/variation-dto.ts
- src/eppo_value.spec.ts
- src/eppo_value.ts
- src/experiment-configuration-requestor.ts
- src/http-client.ts
- src/rule_evaluator.spec.ts
- src/rule_evaluator.ts
- test/testHelpers.ts
- tsconfig.json
Adds support for typed response functions.
* enable strict null checks
* Keeps `getAssignment(...): string`
* Adds `getStringAssignment`, `getBoolAssignment`, `getNumericAssignment`, `getJSONAssignment`
* Created `EppoValue` class
unit tests
> convert to dynamic config; return boolean, numeric and string responses (FF-860)

- package.json
- src/client/eppo-client.ts
---
---
Hit this error while updating the react native sdk. I guess the other js/node sdks weren't relying on `IEppoClient`, but this should be consistent.
```
src/__tests__/index.test.tsx:302:29 - error TS2339: Property 'getParsedJSONAssignment' does not exist on type 'IEppoClient'.
302           const oa = client.getParsedJSONAssignment(subjectKey, experiment);
~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix missing getParsedJSONAssignment property in IEppoClient

- .github/workflows/lint-test-sdk.yml
- .github/workflows/publish.yml
- .npmrc
- package.json
- src/assignment-cache.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/eppo_value.spec.ts
- src/eppo_value.ts
- yarn.lock
Eppo's assignment logger callback is invoked without consideration for duplicate events. These events add cost to our customers to transmit and store the extra data in their warehouses. Additionally, Eppo's computation is slower when processing these additional events.
We will augment the JS SDKs with a cache to mitigate duplicate assignments.
Allows upstream clients to specify an `assignment logger cache` - given a key it will only allow a single invocation of the callback for it.
By default the client-side SDKs will use the `NonExpiringCache` and the nodejs server SDK will instantiate with the …
> assignment logging cache prevents duplicate invocations (FF-1069)

- package.json
- src/client/eppo-client.ts
**Ticket:** [FF-1291 - JavaScript SDK doesn't gracefully handle missing holdouts in the RAC](https://linear.app/eppo/issue/FF-1291/javascript-sdk-doesnt-gracefully-handle-missing-holdouts-in-the-rac)
If an allocation doesn't have a `holdouts` array at all, it hits an error.
* Adjusted test data used by unit tests
> Gracefully handle if allocation has no holdouts field

- package.json
- src/assignment-cache.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/index.ts
… inject their own implementation (FF-839)
---
---
Eppo previously provided 2 implementations of the assignment cache in this library based on generic data structures: `Map` and `LRUCache`. These are non-persistent and cleared between user sessions causing a larger volume of assignment logging then desired.
The goal is to provide persistent cache implementations for our platforms on js browser and react native but these have different APIs: `LocalStorage` and `AsyncStorage`, respectively.
* renaming existing implementations to include `InMemory` as part of the class name for …
> Adds `useCustomAssignmentCache` function to allow upstream clients toinject their own implementation (FF-839)

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
🎟️  **Ticket:** _(Eppo Internal)_ [FF-1557 - JS Client SDK should return null when not initialized](https://linear.app/eppo/issue/FF-1557/js-client-sdk-should-return-null-when-not-initialized)
👯 **Related PR:** [`eppo-client-sdk` #48](https://github.com/Eppo-exp/js-client-sdk/pull/48)
Using `EppoRandomizationProvider` without `waitForInitialization = true` or any other JavaScript pattern where initialization of the client is not `await`ed, could result in some `getInstance()` and `getAssignment()` calls on an uninitialized instance.
Previous changes to `js-client-sdk` made it so that it threw an error ([link](https://github.com/Eppo-exp/js-client-sdk/pull/45/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R218)). However, we want to revert to the behavior of …
> Ability to set configuration request parameters on an already instantiated client instance

- package.json
- src/dto/rule-dto.ts
- src/rule_evaluator.spec.ts
- src/rule_evaluator.ts
- yarn.lock
---
---
RAC API will start returning targeting rule values containing semver strings (https://github.com/Eppo-exp/eppo/pull/8697).
Our SDKs need to be able to parse these strings and perform rule evaluation on them.
The operations `lt, gt, lte, gte` now only apply to numeric values; insert a higher priority step to check if the value is a semver string; if so apply the comparison with it. Otherwise fall through and attempt to evaluate using numerics.
**behavior of un-upgraded SDKs**
They will continue to assume that only numeric values will be present for the `lt, gt, lte, gte` …
> Evaluate targeting rules with semver string format (FF-1433)

- package.json
- src/assignment-cache.ts
- src/lru-cache.spec.ts
- src/lru-cache.ts
- yarn.lock
---
---
A customer is unable to upgrade eppo's latest js sdk versions. 
```
ERROR in ./node_modules/@eppo/js-client-sdk-common/node_modules/lru-cache/dist/commonjs/index.js 27:15
Module parse failed: Unexpected token (27:15)
```
The `lru-cache` package appears to be incompatible for some reason.
Replaces the package with a simple local implementation. Are needs do not require generic types, just a `Map<string, string>` suffices.
New unit test for `LRUCache` class.
[//]: # (Add one or multiple labels: …
> Replace lru-cache package with simple local implementation (FF-1876)

- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/interfaces.ts
- src/rules.spec.ts
- src/rules.ts
- test/writeObfuscatedMockUFC.ts
---
---
- Adding the IS_NULL operator
- Type check return value
- Fix date logic
> [ufc] add null operator and more fixes

- src/client/eppo-client.ts
---
---
No change in functionality. The typed assignment getters should all be explicitly marked as public, for readability.
> Make all typed assignment getters explicitly public

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/flag-configuration-requestor.ts
- src/http-client.spec.ts
- src/http-client.ts
- yarn.lock
1️⃣  the `axios` package cannot be supported in chrome extensions v3 because it is based on APIs that do not exist within a service worker. dogfooding eppo's js sdk within an v3 extension throws this error:
```
http-client.js:32 Uncaught (in promise) Error: There is no suitable adapter to dispatch the request since :
- adapter xhr is not supported by the environment
- adapter http is not available in the build
at HttpClient.handleHttpError (http-client.js:32:1)
at HttpClient.get (http-client.js:25:1)
at async ExperimentConfigurationRequestor.fetchAndStoreConfigurations (experiment-configura…n-requestor.js:10:1)
at async Object.start (poller.js:22:1)
at async EppoJSClient.fetchFlagConfigurations (eppo-client.js:52:1)
at …
```
> Replaced axios with fetch (FF-1976)

- src/version.spec.ts
- src/version.ts
---
---
already out of date 😄 
> make LIB_VERSION dynamic based on package.json value (FF-1998)

- package.json
- src/application-logger.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration-store.ts
- src/configuration-store/configuration-store.ts
- src/configuration-store/hybrid.store.spec.ts
- src/configuration-store/hybrid.store.ts
- src/configuration-store/memory.store.spec.ts
- src/configuration-store/memory.store.ts
- src/flag-configuration-requestor.ts
- src/index.ts
- yarn.lock
Support the migration to alternative upstream storages, such as `chrome.storage.local` or `IndexedDb` by introducing a change to the `setEntries` method of the configuration to allow async writes.
Our goal for now is to maintain the public APIs (`get*Assignment`) as synchronous and this requires keeping the accessor methods sync. This is accomplished by keeping an in-memory sync cache of the configuration.
It is up to upstream libraries to implement against this interface - the shape will look like:
**javascript client - example** 
If the init code detects that `chrome.storage.local` is available (such as in the chromium browsers):
```
class ChromeStorageConfigurationStore {
syncStore: Record<string, T>
asyncStore: …
```
> Convert IConfigurationStore to IAsyncWriteSyncReadStore (FF-1980)

- src/client/eppo-client.ts
- src/poller.spec.ts
- src/poller.ts
…ithout any CDN requests. (FF-2047)
---
---
Users of the JS client SDK (browser) have a desire for an off-line mode that can be paired with providing a custom persistence store implementation that which can be bootstrapped by a server process and reduce client-sourced CDN requests to 0. The serving cache will be populated from this persistent store on startup.
JS clients have polling disabled by default but an initial request is still made.
Adds a new configuration parameter `skipInitialPoll` and implements it in the poller. This paired with previously added support for a custom …
> Add configuration skipInitialPoll to allow the SDK to be configured without any CDN requests. (FF-2047)

- package.json
- src/rules.spec.ts
- src/rules.ts
The NOT_MATCHES operator is missing, add it
Added tests
> [UFC] add missing not_matches operator

- package.json
- src/client/eppo-client.ts
---
---
We need the upstream clients to be able to add the configuration store to an instantiated client inside the `init` method.
> Add builder method to add a configuration store.

- src/index.ts
---
---
Chore: upstream libraries need access to these cache implementations, as well as the `Cacheable` interface to implement their own.
> Export additional assignment cache interfaces. (FF-2110)

- .gitignore
- package.json
- src/configuration-store/memory.store.spec.ts
- src/configuration-store/memory.store.ts
🎟️ **Ticket:** [FF-2268 - JS Common SDK - In Memory Store should kick out removed entries](https://linear.app/eppo/issue/FF-2268/js-common-sdk-in-memory-store-should-kick-out-removed-entries)
When updating entries in a `MemoryStore`, be sure to remove old entries.
> Remove old MemoryStore entries when setting new entries 

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
---
---
Fixes: [EPD-2310](https://linear.app/eppo/issue/EPD-2310/[sdk]-deprecate-getboolassignment-and-create-getbooleanassignment)
The [README](https://github.com/Eppo-exp/js-client-sdk/blob/main/README.md#assign-anywhere) refers to a `getBooleanAssignment` method that doesnt exist.
From Slack discussion:
```
Sven
1 hour ago
Yes I think the JS clients are odd in that they use getBoolAssignment (even though the type is boolean :confused_dog: ) — feel free to update the docs to fix it! :slightly_smiling_face:
felipecsl
[1 hour ago](https://eppo-group.slack.com/archives/C0541NTN6QH/p1717539948841059?thread_ts=1717539554.110119&cid=C0541NTN6QH)
will do!
Aaron
21 minutes ago
OR... hear me out... make the …
```
> fix(sdk): [EPD-2310] 💀 `getBoolAssignment` -> 👶 `getBooleanAssignment`

- package.json
- src/obfuscation.ts
- yarn.lock
---
---
Fixes [FF-2139](https://linear.app/eppo/issue/FF-2139)
Fixes `Property 'atob' doesn't exist` error in React Native 0.72.x
`atob` and `btoa` are not built in to React Native's JS runtime for react-native 0.72. The `atob` and `btoa` were being used by the `universal-base64` package. Replacing this package with `js-base64` provides a [base64 implementation](https://github.com/dankogai/js-base64/blob/main/base64.js) that doesn't rely on atob, btoa or Buffer existing.
- I was able to reproduce the issue by creating a RN 0.72.0 app and testing with XCode / Simulator
- I made the changes in this PR and recompiled assets to `dist`
- I copied over the changed `dist` files, along with the newly installed `js-base64` module to my …
> FF-2139 Fix base64 encoding/decoding for React Native 0.72.x

- package.json
- src/api-endpoint.spec.ts
- src/api-endpoints.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/flag-configuration-requestor.ts
- src/http-client.spec.ts
- src/http-client.ts
- src/index.ts
---
---
This change extracts the API URL building portion out of `FetchHttpClient` into a new class called `ApiEndpoints` which is now exported and allows `js-client-sdk` to then expose the `UFC_ENDPOINT` full URL.
This is a straightforward refactoring with some decoupling and moving stuff out of `FetchHttpClient`. No functionality should have been changed. No API changes either other than exposing a new class.
Bumped minor version due to new external API being introduced.
Existing and new tests
> feat: Expose new `ApiEndpoints` class to return API endpoint URL

- package.json
This reverts commit 0f6cfdb162c9c56ab5f6458890ba29be757f7d18.
We skipped the v3.2.0 release, so I'm reverting this. We didn't end up cutting a release for v3.2.1 since a test was failing.
> Revert "v3.2.1-bump v3.2.1 bump (#77)"

- package.json
- webpack.config.js
- yarn.lock
🎟️ **Ticket:** [FF-2391 - JS Common SDK - Don't use inline source maps](https://linear.app/eppo/issue/FF-2391/js-common-sdk-dont-use-inline-source-maps)
🗨️ **Slack:** "...The first issue is when running our web client app locally with a webpack dev server, the @eppo/js-client-sdk and @eppo/js-client-sdk-common outputs a lot of warnings..."(https://eppo-group.slack.com/archives/C06TTCBDRU4/p1717092945766289?thread_ts=1717091604.044459&cid=C06TTCBDRU4)
When using [`source-map-loader`](https://webpack.js.org/loaders/source-map-loader/) with Wepback, it throws many warnings because it cannot map back to the TypeScript source with what is provided in the `dist` directory.
One way to fix this is to include the TypeScript files as well, as done in an [earlier …
> Aaron/ff 2391/source maps

- package.json
- src/cache/assignment-cache.ts
- src/index.ts
---
---
This needs to be exported so users can implement custom assignment cache versions.
This will be used by js-client-sdk (PR incoming)
FF-2113
Existing tests
> chore: Export `AbstractAssignmentCache`

- src/bandit-evaluator.spec.ts
- src/bandit-evaluator.ts
- src/client/eppo-client.spec.ts
- src/configuration-requestor.spec.ts
- src/configuration-requestor.ts
- src/evaluator.ts
- src/http-client.ts
- src/index.ts
- src/types.ts
🎟️ **Ticket:** [FF-2407 - JS SDK - Bandit evaluator weigh actions](https://linear.app/eppo/issue/FF-2407/js-sdk-bandit-evaluator)
🗺️ **Design Review:** [Bandits Engineering Design](https://www.notion.so/eppo/Bandits-Engineering-Design-c5df5b6072b446aa8cacbf54e4d1f9df?pvs=4)(Relevant section: [Action Selection](https://www.notion.so/eppo/Bandits-Engineering-Design-c5df5b6072b446aa8cacbf54e4d1f9df?pvs=4#1ccc9845e4af42f78ad5ff08f304d402))
This pull request layers in the logic and tests for scoring and weighing bandit actions based on the context. The context compromises numeric and categorical attributes belonging to the subject being assigned and the action being considered.
After this pull request, future changes include:
- Deterministic shuffling and selection of an …
> Aaron/ff 2407/bandit evaluator

- .vscode/settings.json
- src/client/eppo-client.ts
- src/index.ts
This is the first part of the "Evaluation Reasons" work. This PR entail removal of IEppoClient to make it easier to add functions to EppoClient. `IEppoClient` was an unnecessary interface (discussion: https://eppo-group.slack.com/archives/C04KR1GGE3C/p1718890880706789)
> FF-2465 Evaluation Reasons

- package.json
- src/index.ts
---
---
To support a customer request where they will be downloading the configuration outside of the JS SDK in obfuscated mode but need to bootstrap the JS SDK during sync initialization.
The configuration for this new method will be:
```
export interface IClientConfigSync {
flagsConfiguration: Record<string, Flag | ObfuscatedFlag>;
assignmentLogger?: IAssignmentLogger;
isObfuscated?: boolean;
throwOnFailedInitialization?: boolean;
}
```
We need to have the `ObfuscatedFlag` type available in the JS SDK.
Exports `ObfuscatedFlag`.
[//]: # (Please describe in detail how you tested …
> feat: [export ObfuscatedFlag] (FF-2456)

- src/client/eppo-client.ts
We need to enable customers to export configuration from their servers (with not obfuscated configuration) and bootstrap their clients (which default to obfuscated mode).
Allows the client to be instantiated in the desired obfuscation mode.
I noticed `false` is the default - I'm not sure a default is desirable at all. The upstream clients should provide the default?
> feat: [allow SDK to switch between obfuscation modes] (FF-2455)

- package.json
- src/api-endpoint.spec.ts
- src/api-endpoints.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/constants.ts
- src/http-client.spec.ts
- src/http-client.ts
- src/index.ts
---
---
Export `ApiEndpoints` so we can expose a `getConfigUrl` method in the client SDK
Intended usage in js-client-sdk
```javascript
import { sdkName, sdkVersion } from './sdk-data';
export function getConfigUrl(apiKey: string, baseUrl?: string): URL {
const queryParams = { sdkName, sdkVersion, apiKey };
return new ApiEndpoints({ baseUrl, queryParams }).ufcEndpoint();
}
// And when this method is called, it returns the fully formed URL
getConfigUrl('abcd1234') --> "https://fscdn.eppo.cloud/api/flag-config/v1/config?apiKey=abcd1234&sdkVersion=3.1.4&sdkName=js-client-sdk"
// And …
```
> feat: [export api endpoints class] (ff 2310)

- src/bandit-evaluator.spec.ts
- src/bandit-evaluator.ts
- src/bandit-logger.ts
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/constants.ts
- test/testHelpers.ts
After PRs #85 and #88, we fetch bandit parameters, use them to score actions, and then weigh the probabilities of those actions so they collectively add up to `1.0`.
This PR builds on that by shuffling and then selecting a weighted action to assign, as well as logging the result.
The [shared test cases pass](https://github.com/Eppo-exp/sdk-test-data/tree/main/ufc/bandit-tests), as well as some newly-added client-specific ones, such as making sure the right stuff is being passed to the logger.
> Bandit selects and assigns action from weighted actions

- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/flag-evaluation-details.ts
[FF-2498](https://linear.app/eppo/issue/FF-2498/evaluation-reasons-node-server-sdk-basic-match-reason-functionality)
This improves the developer experience by allowing users to see how a variation is assigned. 
New "Details" assignment functions return an object with metadata that allows end-users to understand how a variation is defined.
- getBooleanAssignmentDetails
- getIntegerAssignmentDetails
- getJSONAssignmentDetails
- getNumericAssignmentDetails
- getStringAssignmentDetails
Below is an example of the object returned:
```
{
"value": "C", // would be provided default value if variationValue is null
"variationKey": "experiment-c",
"variationValue": "C",
"flagEvaluationCode": "MATCH",
"flagEvaluationDescription": "Supplied attributes match rules defined in 'allocation-32'", …
```
> FF-2498 Evaluation Details, excluding config fetch/publish time

- src/client/eppo-client.ts
- src/flag-evaluation-details.ts
This was meant to be added to https://github.com/Eppo-exp/js-client-sdk-common/pull/99 before it was merged in to the `greg/FF-2465/evaluation-reasons` base branch. These are code review changes.
> FF-2498 Fix `this.unevaluatedAllocations` for "none"; fix comment

- src/client/eppo-client.spec.ts
- test/testHelpers.ts
This will leverage the the new "assignmentDetails" test data in https://github.com/Eppo-exp/sdk-test-data/pull/30. Tests will not work until that PR is merged in.
Test failures for assignment details will look like this:
> FF-2465 "Assignment Details" tests

- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration-store/configuration-store.ts
- src/configuration-store/hybrid.store.ts
- src/configuration-store/memory.store.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/flag-configuration-requestor.ts
- src/flag-evaluation-details.ts
- src/http-client.ts
- test/testHelpers.ts
[FF-2501](https://linear.app/eppo/issue/FF-2501)
js-client-sdk implements this functionality in https://github.com/Eppo-exp/js-client-sdk/pull/90
Implements `configFetchTime` and `configPublishTime` to give users a better understanding of which version of the configuration is loaded.
Integration testing
> FF-2501 Include config fetch/publish time with assignment details

- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration-requestor.spec.ts
- src/configuration-requestor.ts
- src/http-client.ts
- src/interfaces.ts
- test/testHelpers.ts
🎟️ **Ticket:** [FF-2519 - JS SDK - Update for updated shared bandit test cases](https://linear.app/eppo/issue/FF-2519/js-sdk-update-for-updated-shared-bandit-test-cases)
Update this repository to handle the updated formatting and updated shared bandit test cases ([`sdk-test-data` #36](https://github.com/Eppo-exp/sdk-test-data/pull/36)).
For the no-actions-provided one to work, we need another configuration store to keep track of which flags have active bandits.
Note: Automated tests are expected to fail now; they should pass once updated test data is merged.
> Update for updated shared test data

- src/assignment-logger.spec.ts
- src/assignment-logger.ts
- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/evaluator.ts
- src/flag-evaluation-details-builder.ts
- test/testHelpers.ts
Implements [FF-2465](https://linear.app/eppo/issue/FF-2525/evaluation-reasons-include-details-in-assignment-logger)
Most people who are using the assignment logger are doing it to gain more insight on the assignments. It makes sense to include the "details" as well so that they have access to all the information available.
Added "details" to assignment, cleaned up imports, and renamed interfaces to follow convention.
> FF-2525 Add Assignment Details to logger

- src/assignment-logger.spec.ts
- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration-store/configuration-store.ts
- src/configuration-store/hybrid.store.ts
- src/configuration-store/memory.store.ts
- src/decoding.spec.ts
- src/decoding.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/flag-configuration-requestor.ts
- src/flag-evaluation-details-builder.ts
- src/http-client.ts
- src/interfaces.ts
[FF-2465](https://linear.app/eppo/issue/FF-2526/evaluation-reasons-include-environment-and-allocationname-in-details)
This change was motivated by internal feedback.
Adds `environment` and `assignments[].name` to the new "assignment details" functionality. 
verified test data works with updated change
Manual testing:
> FF-2465 adds "environment" and "allocation.name" to details

- src/assignment-logger.spec.ts
- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client.spec.ts
- src/decoding.spec.ts
- src/decoding.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/flag-evaluation-details-builder.ts
- src/interfaces.ts
- tsconfig.json
This removes support for `allocation.name` in the "Evaluation Reasons" feature to ensure that potentially sensitive data is not exposed.
Tests will pass after https://github.com/Eppo-exp/sdk-test-data/pull/43 is merged
> FF-2526 removes `name` from `AllocationEvaluation`

- src/bandit-evaluator.spec.ts
- src/bandit-evaluator.ts
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/index.ts
- src/types.ts
- test/testHelpers.ts
🎟️ **Ticket:** [FF-2511 - JS SDK - Support explicitly passed numeric/categorical attributes](https://linear.app/eppo/issue/FF-2511/js-sdk-support-explicitly-passed-numericcategorical-attributes)
Sometimes, it may not be obvious if an attribute is numeric or categorical (e.g., area code, zip code, group number, etc.), so we provide the ability for clients to be specific about which attributes are numeric or categorical.
In addition to the existing types:
```ts
export type AttributeType = string | number | boolean;
export type Attributes = { [key: string]: AttributeType };
```
We define some new types:
```ts
export type ContextAttributes = {
numericAttributes: Attributes;
categoricalAttributes: Attributes;
};
export type BanditSubjectAttributes = Attributes | …
```
> Handle explicitly bucketed numeric and categorical attributes 

- package.json
- src/bandit-logger.ts
- src/client/eppo-client.ts
- src/index.ts
- src/types.ts
_Eppo Internal_:
🎟️ **Ticket:** [FF-2585 - Export common bandit logger types](https://linear.app/eppo/issue/FF-2584/node-sdk-export-common-bandit-logger-types)
It's useful for developers to have public access to the types used to define attributes, bandit attributes, and actions.
> export bandit types

- .vscode/settings.json
- package.json
- src/assignment-logger.spec.ts
- src/assignment-logger.ts
- src/bandit-logger.ts
- src/cache/lru-cache.ts
- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.ts
- src/configuration-requestor.ts
- src/configuration-store/configuration-store.ts
- src/configuration-store/hybrid.store.ts
- src/configuration-store/memory.store.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/flag-evaluation-details-builder.ts
- src/http-client.ts
- src/index.ts
- src/interfaces.ts
- test/testHelpers.ts
- tsconfig.json
**Evaluation Reasons - js-client-sdk-common** 
[Evaluation Reasons - js-client-sdk](https://github.com/Eppo-exp/js-client-sdk/pull/90)
[Evaluation Reasons - node-server-sdk](https://github.com/Eppo-exp/node-server-sdk/pull/62)
[Evaluation Reasons - react-native-sdk](https://github.com/Eppo-exp/react-native-sdk/pull/51)
This is the main branch for the "Evaluation Reasons" work. Other PRs related to this feature will be merged into this branch before this branch is merged into `main`. This will not be mergeable until other work has been merged into this branch.
Implements: [FF-2465](https://linear.app/eppo/issue/FF-2465/evaluation-reasons-js-client-sdk-common)
See [Design …
> feat: Evaluation Details

- package.json
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.ts
- src/flag-evaluation-details-builder.ts
Flag assignments should not depend on allocations that are not reached. Today, `getBanditAction` violates this principle because it will short-circuit and return the default value even when a valid (non-bandit) allocation would have been selected.
This PR changes the behavior of `getBanditAction` when it is called with no actions. Before this change, `getBanditAction` would always return the default value, even when the bandit variation was not being assigned. With this change, it only returns `default` when the bandit variation is assigned, and hence the default is chosen because the bandit has no actions to choose from.
Full example of a flag `landing-page` that shows the change in behavior. In order, its allocations are:
1. (Manual targeting rule) If `isInternalUser == true`, then …
> Do not override non-bandit assignments when getBanditAction is called with no actions

- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client.ts
See also: [sdk-test-data updates](https://github.com/Eppo-exp/sdk-test-data/pull/47). Tests will pass once that PR is merged.
Fixes: [FF-2846](https://linear.app/eppo/issue/FF-2846/jsnode-sdk-incorrect-assignment-type-returned-in-evaluation-details)
(see ticket)
- If user specifies incorrect assignment type (e.g., boolean instead of string), ASSIGNMENT_ERROR is returned instead of expected TYPE_MISMATCH
- When there’s an (internal) error in configuration when flag.variationType does not match variation’s value, TYPE_MISMATCH is returned when ASSIGNMENT_ERROR is more fitting
Calling getIntegerAssignmentDetails for a non-numeric variation now returns a `flagEvaluationCode` of `TYPE_MISMATCH` instead of `ASSIGNMENT_ERROR`. A misconfigured variation now returns an `ASSIGNMENT_ERROR` instead …
> fix: incorrect evaluation details code returned for TYPE_MISMATCH

- src/client/eppo-client.ts
- src/evaluator.ts
- src/flag-evaluation-details-builder.ts
- src/flag-evaluation-error.ts
Fix for test updates in https://github.com/Eppo-exp/sdk-test-data/pull/49. Tests will pass once that PR is merged.
> fix: preserve allocation evaluation details for ASSIGNMENT_ERROR

- package.json
- src/bandit-evaluator.ts
_Eppo Internal_
🎟️ **Ticket:** [FF-3004 - Tie break top scoring bandit actions by action name](https://linear.app/eppo/issue/FF-3004/js-common-sdk-tie-break-top-scoring-bandit-actions-by-action-name)
There are certain situations where actions can be tied for the top score. In these situations, we want to deterministically declare a winner, as its weight is computed differently than the others. Currently, in this SDK, the winner is based on the order in which the actions are passed to the bandit--which is not what we want.
This situation is recreated in a newly added test case for our shared test data ([PR link](https://github.com/Eppo-exp/sdk-test-data/pull/52))
When determining the top-scoring action, prioritize actions with alphabetically earlier names.
Will be tested by the new shared …
> Tie break top-scoring bandit actions by action name

- package.json
- src/cache/abstract-assignment-cache.spec.ts
- src/cache/abstract-assignment-cache.ts
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.ts
🎟️ **Ticket:** [FF-3112 - JS Common SDK - Assignment cache should work at the bandit action level](https://linear.app/eppo/issue/FF-3112/js-common-sdk-assignment-cache-should-work-at-the-bandit-action-level)
🗨️ **Slack:** ["...are subsequent calls of the SDK assignment function still sending those events to the logger..."](https://eppo-group.slack.com/archives/C07GZEQA6GH/p1724359798605419)
Customers may optionally want to exclude repeat bandit assignments from executing the logger callback to reduce the number of entries sent to their data warehouse.
This PR mirrors the flag assignment cache functionality for bandit actions. The difference is that the unique and cached value is a function of the bandit key and action key instead of the allocation key and variation key. …
> Add bandit assignment cache

- .github/workflows/publish.yml
- package.json
Fixes upload artifact job and bumps version for new `getExperimentContainer` function
> chore: use latest actions/upload-artifact github action

- src/client/eppo-client-with-bandits.spec.ts
- src/configuration-requestor.spec.ts
---
---
`"modelVersion": "v123",` became `"modelVersion": "123",` in https://github.com/Eppo-exp/sdk-test-data/pull/71
This updates the tests to match this format so they pass again
> fix: bandit model version in tests

- .github/workflows/lint-test-sdk.yml
Run CI checks on a matrix of node versions
> chore(ci): Run CI on node test matrix

- package.json
- src/client/eppo-precomputed-client.spec.ts
- src/client/eppo-precomputed-client.ts
- src/http-client.ts
- src/interfaces.ts
- src/precomputed-requestor.spec.ts
- src/precomputed-requestor.ts
---
---
Previously was doing a GET request
I confirmed the POST request works by running a script that calls `client.fetchPrecomputedFlags` and then checking that the `getBooleanAssignment` method works with an expected flag and assignment
> fix: post with http client

- .eslintrc.js
- package.json
- src/client/eppo-client.ts
- src/evaluator.ts
- src/events/array-backed-named-event-queue.ts
- src/events/batch-event-processor.spec.ts
- src/events/batch-event-processor.ts
- src/events/batch-retry-manager.ts
- src/events/bounded-event-queue.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
- src/events/event-delivery.ts
- src/events/event-dispatcher.ts
- src/events/named-event-queue.ts
- src/events/network-status-listener.ts
- src/events/no-op-event-dispatcher.ts
- src/index.ts
- tsconfig.json
- yarn.lock
Towards: FF-3567
Add ability to track and deliver arbitrary events to an ingestion URL
* Create `EventDispatcher` to encapsulate event queueing and delivery attempts
* Added retry mechanism with `BatchRetryManager` with configurable settings
* Added `NetworkStatusListener` interface (implementation will be platform specific) to handle online/offline mode
* Upload events in batches of configurable size
Wrote tests
> feat(events): Add `EventDispatcher` and related classes

- .eslintrc.js
- package.json
- src/client/eppo-client.ts
- src/events/bounded-event-queue.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
- src/events/event-delivery.ts
- src/index.ts
- yarn.lock
Fixes: FF-3604
This change accomplishes mainly 2 things:
* Provide a public API so that consumers of this library can set an instance of `EventDispatcher` into the `EppoClient`
* Provide default config values for `DefaultEventDispatcher` instance via factory function
* Parse ingestion URL out of SDK key and set it into the config
Wrote tests
> feat: Add public API for setting event dispatcher

- package.json
- src/api-endpoints.ts
- src/assignment-logger.spec.ts
- src/assignment-logger.ts
- src/client/eppo-client.ts
- src/client/eppo-precomputed-client.spec.ts
- src/client/eppo-precomputed-client.ts
- src/configuration-requestor.ts
- src/configuration-store/configuration-store-utils.ts
- src/configuration-store/configuration-store.ts
- src/configuration-store/hybrid.store.ts
- src/configuration-store/memory.store.ts
- src/constants.ts
- src/decoding.ts
- src/evaluator.spec.ts
- src/evaluator.ts
- src/http-client.ts
- src/index.ts
- src/interfaces.ts
- src/precomputed-requestor.spec.ts
- src/precomputed-requestor.ts
> feat: create EppoPrecomputedClient

- package.json
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
---
---
This is actually a valid use case for sdk keys created prior to event gateway creation
Fallback to no-op implementation
Updated tests
> fix: Do not throw from `newDefaultEventDispatcher` on invalid key

- package.json
- yarn.lock
Fixes: FF-3645
Add `buffer` fork polyfill with support for `base64url` encoding.
Code is here https://github.com/Eppo-exp/buffer/tree/add-base64url-support
Source: https://github.com/feross/buffer/pull/314 (once this is merged, we can revert back to the main buffer repo)
Make sure we polyfill `buffer` for browser environment and it has support for `base64url`.
Thanks @maya-the-mango for reporting and helping with debugging
* Started a new next.js repo and added a dependency on `"@eppo/js-client-sdk": "^3.8.0",`
* Also added resolution to this fork:
```
"resolutions": {
"@eppo/js-client-sdk-common": "git+https://github.com/eppo-exp/js-sdk-common#felipecsl--buffer-polyfill"
}
```
called `init` and verified no errors thrown
> fix: Add buffer polyfill with `base64url` support

- package.json
- src/events/sdk-key-decoder.spec.ts
- src/events/sdk-key-decoder.ts
Replace usage of `Buffer` with `js-base64` polyfill for browser environment
It looks like `Base64.decode` is able to parse both flavors of base64-encoded strings (regular and url-safe `'base64url'` encoding), so this is a safe change. The docs also mention that explicitly https://github.com/dankogai/js-base64?tab=readme-ov-file#synopsis
Wrote another test
Related to https://github.com/Eppo-exp/js-client-sdk/pull/115
> fix: Use js-base64 polyfill instead of `Buffer` for browser env

- package.json
- src/bandit-evaluator.spec.ts
- src/bandit-evaluator.ts
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.ts
---
---
Fixes: FF-3669
Coinbase would like the ability to get the best action (rather than a probabilistic selection) for situations like when they are indexed by Google Crawlers.
- `BanditEvaluator.evaluateBestBanditAction`, new method to score and weigh the bandits, then select the highest scoring action
- `EppoClient.getBestBanditAction`, to provide a means to select the best action.
> feat: getBestBanditAction

- src/events/array-backed-named-event-queue.ts
- src/events/batch-event-processor.spec.ts
- src/events/batch-event-processor.ts
- src/events/batch-retry-manager.ts
- src/events/bounded-event-queue.spec.ts
- src/events/bounded-event-queue.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
- src/events/event-delivery.ts
- src/events/named-event-queue.ts
- yarn.lock
Fixes: FF-3628
Avoid data loss when event delivery retry fails after `maxRetries`
Re-add events at the end of the queue if they failed delivery after `maxRetries` to avoid data loss.
Wrote test
> fix(events): Re-enqueue failed retries after `maxRetries`, bump `eslint`

- src/client/eppo-client.ts
- src/events/batch-event-processor.spec.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/event-dispatcher.ts
---
---
Follow up from discussion here https://github.com/Eppo-exp/js-sdk-common/pull/162#discussion_r1876459822
Event payload `unknown` -> `Record<string, unkown>`
Existing tests
> chore: Ensure event payload is an object

- src/events/default-event-dispatcher.ts
- src/events/sdk-key-decoder.spec.ts
- src/events/sdk-key-decoder.ts
Make sure the event ingestion URL is valid
The browser will do this if we don't explicitly set a URL scheme
Updated tests
> fix(events): Prefix event ingestion URL with scheme if none provided

- package.json
- src/client/eppo-precomputed-client.ts
---
---
It's probably not an issue, but just to be safe, it's probably better to keep this method around until there's a major version bump since it is used here https://github.com/Eppo-exp/js-client-sdk/blob/d584a9e1bed0f2da756121bd0b84044c174b9909/src/index.ts#L598
> fix: keep setPrecomputedFlagsRequestParameters

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/client/eppo-precomputed-client.spec.ts
- src/configuration.ts
- src/http-client.ts
- src/index.ts
- src/interfaces.ts
- src/obfuscation.ts
- src/precomputed-requestor.ts
---
---
Towards: FF-3657
We need the node-server to produce a set of precomputed flags which can be ingested by an `EppoPrecomputedClient`. This format is already established by the current edge-compute function and leveraged by this implementation
New method
```ts
EppoClient {
getPrecomputedAssignments(subject, subjectAttributes, obfuscated = false): IPrecomputedFlagsResponse
}
```
- new unit tests
> feat: ability to export precomputed assignments

- src/events/batch-event-processor.spec.ts
- src/events/batch-event-processor.ts
- src/events/batch-retry-manager.spec.ts
- src/events/batch-retry-manager.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
- src/events/event-delivery.spec.ts
- src/events/event-delivery.ts
- src/events/event-dispatcher.ts
- src/events/event.ts
- src/events/no-op-event-dispatcher.ts
- src/index.ts
---
---
Fixes: FF-3686
Event ingestion API returns an array of event UUIDs that failed delivery.
Re-enqueue those for delivery.
* Parse the response body from the event ingestion URL
* Find any UUIDs that failed delivery and re-enqueue for retry
* Also take into account failed UUIDs when handling retries
Wrote tests
> feat(events): Redeliver subset of failed events from a batch

- src/events/batch-event-processor.spec.ts
- src/events/batch-event-processor.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
---
---
Make sure we enforce a sane batch size for event ingestion
batchSize will be always between 100 and 10k
Wrote test
> chore(events): Clamp `batchSize` between [min, max]

- package.json
- src/configuration-requestor.ts
- src/evaluator.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/no-op-event-dispatcher.ts
- src/flag-evaluation-details-builder.ts
- src/obfuscation.spec.ts
- src/obfuscation.ts
- test/testHelpers.ts
🎟️ **Ticket:** [FF-3763 - Update shared SDK test data to have a test case for special characters](https://linear.app/eppo/issue/FF-3763/update-shared-sdk-test-data-to-have-a-test-case-for-special-characters)
🗨️ **Slack Thread:** ["...flag text encoding problem..."](https://eppo-group.slack.com/archives/C0541NTN6QH/p1735566355776199)
The JavaScript core library currently does not handle special, non-ASCII characters.
We switch from using [`js-base64`](https://www.npmjs.com/package/js-base64)'s `btoaPolyfill()` and `atobPolyfill()` to `encode` and `decode` respectively.
The former is designed only to handle ASCII characters and bytes ([docs](https://github.com/dankogai/js-base64?tab=readme-ov-file#decode-vs-atob-and-encode-vs-btoa)), while the latter is designed for strings …
> Handle special characters when decoding obfuscated configurations

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/index.ts
- src/obfuscation.ts
- src/react-native-get-random-values.d.ts
- tsconfig.json
- webpack.config.js
- yarn.lock
---
---
A method for exporting precomputed assignments was added to the common sdk https://github.com/Eppo-exp/js-sdk-common/pull/160 and published in [version 4.7.1](https://github.com/Eppo-exp/js-sdk-common/releases/tag/v4.7.1)
The end-user would use the function in the node SDK and so I checked that it works in the node environment. I found a couple things to improve:
* `crypto` needs to be imported in node, the common sdk assumes it is a globally scoped variable which is only true in the browser environment
* the common sdk is hard coded to assume that precomputed assignments …
> chore: adjust precomputed assignments export for node environment

- package.json
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration.ts
- src/index.ts
- src/obfuscation.spec.ts
- src/obfuscation.ts
- src/react-native-get-random-values.d.ts
- tsconfig.json
- webpack.config.js
- yarn.lock
---
---
This reverts commit 12f29832b2022099052c2c738dab28822864a7a7 and changes where we generate the salt to the node server sdk: https://github.com/Eppo-exp/node-server-sdk/pull/89/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80.
Removes salt generation code from the common sdk, so we don't need to worry about supporting the `crypto` module in all environments where this is run: js in a browser, node in a server, and react native.
We only need the ability to generate the precomputed configuration in the node server sdk, so I adjusted …
> chore: remove dependency on crypto module in common

- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
> fix: check that config store is initialized before skipping fetch

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
Reverts Eppo-exp/js-sdk-common#193
Breaks tests in downstream SDKs.
The `initialized` boolean more accurately indicates "a fetch has written entries to this persistent store in this instance/javascript frame"
- Reverts #193
- bumps patch version.
> Revert "fix: check that config store is initialized before skipping fetch"

- package.json
- src/client/eppo-precomputed-client.ts
---
---
Bandit events were not being flushed when setting the logger.
Mirror types and behavior of flag assignment logger.
> chore: Fix bandit events queue.

- src/client/eppo-precomputed-client.ts
- src/decoding.spec.ts
- src/decoding.ts
- src/obfuscation.spec.ts
> decode to number, tests, nit

- package.json
- src/client/eppo-client.ts
- src/index.ts
👯‍♀️ Related PRs:
[js-client#166](https://github.com/Eppo-exp/js-client-sdk/pull/166/files)
This makes it easier to subclass the `EppoClient` in the downstream SDKs.
> feat: Create and export a type for the EppoClient constructor

- package.json
- src/index.ts
- src/obfuscation.spec.ts
- src/obfuscation.ts
---
---
Fixes: FF-3920
This method is used by both react-native and js-client SDKs so rather than duplicate, we'll move it to common. Also, this moves the algorithm to use a hash instead of just slicing the API key to avoid leaking sensitive info. This also makes suffix collisions much less likely
> feat: move `buildStorageKeySuffix`  function to common and bump release

- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/events/batch-retry-manager.spec.ts
- src/events/batch-retry-manager.ts
- src/events/default-event-dispatcher.spec.ts
- src/events/default-event-dispatcher.ts
- src/events/event-delivery.spec.ts
- src/events/event-delivery.ts
- src/events/event-dispatcher.ts
- src/events/no-op-event-dispatcher.ts
---
---
Fixes: FF-3932
Allow attaching `context` keys and values with events dispatched through the Track API.
Context are optional "global" key/value pairs associated with all events and delivered with the Track API to the ingestion endpoint.
Wrote tests
> feat(events): Add event context

- package.json
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/client/eppo-precomputed-client.spec.ts
- src/client/eppo-precomputed-client.ts
- src/constants.ts
- src/evaluator.ts
If overrides have been supplied, use those instead of evaluating rules. Leverages a user-supplied configuration store if present, which may be backed by memory or local storage.
> feat: add local override functionality

- src/client/eppo-client-with-overrides.spec.ts
- src/client/eppo-client.ts
- src/override-validator.ts
- src/util.ts
Allows users to override server-side flags by providing new `parseOverrides` and `withOverrides` functions to the EppoClient. 
- `parseOverrides` - Allows users to parse the `x-eppo-overrides` header sent by web requests. Eppo's Chrome extension will intercept and append this header to all https endpoints for the target site. 
- `withOverrides` - Creates an EppoClient instance that has overrides applied so that it doesn't affect the behavior of the original EppoClient singleton on a shared Node web server.
Typical usage will be something like this:
```typescript
export const eppoOverridesStorage = new AsyncLocalStorage<Record<FlagKey, Variation>>();
@Injectable()
export class EppoOverridesMiddleware implements NestMiddleware {
use(req: Request, res: Response, next: NextFunction) { …
```
> feat: server overrides

- package.json
- src/client/eppo-precomputed-client.spec.ts
- src/client/eppo-precomputed-client.ts
---
---
There is a place in `EppoPrecomputedJSClient`'s implementation where we want to initialize the instance with an empty store.
https://github.com/Eppo-exp/js-client-sdk/blob/5b317dab2cda07abb8aa259a14e7f88ac1dfc963/src/index.ts#L680-L688
This results in the following two errors getting logged
```
"[Eppo SDK] EppoPrecomputedClient requires an initialized precomputedFlagStore if requestParameters are not provided"
"[Eppo SDK] EppoPrecomputedClient requires a precomputedFlagStore with a salt if requestParameters are not provided"
```
Even if the client isn't even using the precomputed client, since we are initializing …
> fix: remove unnecessary precomputed constructor error logs

- package.json
- src/client/eppo-precomputed-client-with-bandits.spec.ts
- src/client/eppo-precomputed-client.ts
Tests will pass after https://github.com/Eppo-exp/sdk-test-data/pull/123 is merged
Fixes scenario where a bandit flag is assigned to a non-bandit variation. Instead of returning the programmatic default, we want to return the assigned variation when `getBanditAction` is called.
See also: https://github.com/Eppo-exp/sdk-test-data/pull/123
> fix: non-bandit flags return string assignment

- package.json
- src/http-client.ts
Fixes issues caused by the implementation of https://github.com/Eppo-exp/js-sdk-common/pull/242 where URL.pathname was not available in older React Native JS runtimes.
> fix: Network Error in older React Naitve versions

- package.json
- src/client/eppo-client.ts
- src/configuration-wire-types.spec.ts
- src/configuration-wire-types.ts
---
---
Towards FF-4076
📜 [Configuration Side Loading](https://www.notion.so/eppo/Configuration-side-loading-design-12249cc0114380bc9650d8dc4e189e77)
Client is looking to use offline init with the node-server SDK as indicated by our docs, however said feature does not exist.
This change implements TODOs in the `IConfigurationWire` type
- Add fields for Flag and Bandit config responses
- Create type safety around the response payload strings
- unit tests
> feat: IConfiguration definitions for UFC and type safety

- .eslintrc.js
- src/api-endpoints.ts
- src/http-client.ts
---
---
Fixes: [FF-4133](https://linear.app/eppo/issue/FF-4133/ban-url-instances-in-js-client-sdk-common)
There are a number of issues with the `URL` implementation in React Native's Heremes JavaScript engine:
- URL cannot handle "localhost" domain for base url [react-native#26019](https://github.com/facebook/react-native/issues/26019).
- URL implementation should add a trailing slash to the base [react-native#25717](https://github.com/facebook/react-native/issues/25717).
- URL incorrectly adds trailing slash [react-native#24428](https://github.com/facebook/react-native/issues/24428).
Creating an instance of URL like: new URL('http://facebook.com') throws an exception …
> chore: ban URL due to incompatibilities with React Native's Hermes JS engine

- package.json
- src/client/eppo-client.ts
The deprecation of `isObfuscated` led to the desire to emit a warning when the SDK may be acting out of expected vis a vis _obfuscated_ state of the config. The implementation left a lot to be desired and had some bugs. 
- Emit an _info_ level log when setting `isObfuscated`
- Drop all `isObfuscatedCache` and warning on mismatch
- bump patch version
- Also fix `EppoClientParameters` to have new `overrides` field and restore use of `EppoClientParameters` type in constructor. This was broken in #184
> fix: simplify `isObfuscated` messaging

- package.json
- src/client/eppo-client.ts
- src/configuration-requestor.spec.ts
- src/configuration-requestor.ts
---
---
Fixes FF-4161
Not updating the Config Stores on the Config Requestor means that the dev can call `setFlagConfigurationStore` without any effect. This actually causes test failures downstream where we are using and abusing the same client instance for all the tests.
**This bug is blocking integrating the latest common downstream.**
- allow config stores to be updated on the Config Requestor.
- new unit tests
- verified to fix downstream testing failures
> fix: Update configuration stores in `ConfigurationRequestor` when they are changed on the client

- Makefile
- src/client/eppo-client-with-bandits.spec.ts
- src/client/eppo-client.spec.ts
- src/client/eppo-client.ts
- src/configuration-wire/configuration-wire-types.spec.ts
- src/configuration-wire/configuration-wire-types.ts
- src/configuration-wire/json-util.ts
- src/index.ts
- test/testHelpers.ts
> chore:refactor JSON utils, add configurationFromString method for exporting

- src/client/eppo-client-assignment-details.spec.ts
- src/client/eppo-client.spec.ts
- src/evaluator.ts
- src/http-client.ts
- test/testHelpers.ts
🎟️ [FF-4335 - Update JS Common Tests for Evaluation Details](https://linear.app/eppo/issue/FF-4335/update-js-common-tests-for-evaluation-details)
Our JavaScript SDKs have `getXXXXXXXDetails()` methods, so we should ensure the details are being correctly populated.
Expand `eppo-client.spec.ts` to include checking details by using data providers.
(no documentation needed for adding tests)
This _is_ the tests 😛
> Update automated tests to also check evaluation details

- package.json
- src/poller.ts
---
---
[//]: # (Please describe how you documented the developer impact of your changes; link to PRs or issues or explan why no documentation changes are required)
> [FFL-648] stop polling

- package.json
- src/application-logger.ts
- src/client/eppo-client.ts
- src/client/eppo-precomputed-client.ts
- src/events/event-delivery.ts
👯  Related PR: [`js-client-sdk #257`](https://github.com/Eppo-exp/js-client-sdk/pull/257#pullrequestreview-3302101524)
_Eppo Only:_
🎟️ **Tickets:**
* [FFL-780 - Don't assume process (and process.env) exists in js-sdk-common application logger](https://datadoghq.atlassian.net/browse/FFL-780)
* [FFESUPPORT-100 - Legacy Eppo Browser SDK has browser logging hard-coded off](https://datadoghq.atlassian.net/browse/FFESUPPORT-100)
This common repository is shared with the Node.js and Browser JavaScript SDKs. The latter won't have a global `process`, causing errors unless a dummy global `process` is defined.
Also, currently, logging is hard-coded to be off (silent) for the Browser SDK. However, having logs can be helpful, especially for debugging.
This PR does not assume `process` will be defined. …
> Fix browser logging fixes
