src/client/eppo-client.spec.ts

---
---
Propagating this feedback into the other JS/Node SDK's tests: https://github.com/Eppo-exp/react-native-sdk/pull/6#discussion_r1338794702

Consolidate getAssignmentsWithSubjectAttributes and getAssignments into one function

---

package.json

version 1.5.2

---

.github/workflows/publish.yml

Change action yml to yarn publish

---

.github/workflows/publish.yml

Update npm-publish to v3

---

.github/workflows/publish.yml
package.json

Add step to log errors

---

package.json

Update package.json to 2.2.2

---

README.md

Instruction for local development

---

.github/workflows/lint-test-sdk.yml
.github/workflows/publish.yml
package.json
yarn.lock

---
---
nodejs 16 is eol (https://nodejs.org/en/about/previous-releases)

require node >=18.20 (FF-1876)

---

src/client/eppo-client.ts
src/index.ts

---
---
* Use application logging globally, no more usage of `console.log`, so that logs are not emitted into the browser
* Allow upstream libraries (js, nodejs) to use pino

switch logging to pino

---

package.json
src/index.ts

---
---
Forgot to export these - needed by upstream libraries to implement `chrome.storage` and `localStorage` based implementations.

export configuration store interfaces

---

package.json
src/index.ts

export MemoryStore

---

src/client/eppo-client.spec.ts
test/testHelpers.ts

---
---
I was investigating these test failures just for my own learning and decided to submit some drive-by fixes, just minor cleanup, no functionality was changed.
Test only cleanup.
Existing tests

chore(tests): Minor test cleanup

---

src/configuration-store/configuration-store.ts
src/configuration-store/hybrid.store.ts
src/configuration-store/memory.store.ts

---
---
Pulling this changes out of #83 - https://github.com/Eppo-exp/js-client-sdk-common/pull/83/files#r1635880392
Simple cleanup, no functionality affected.
Existing tests

chore: Cleanup `IConfigurationStore` interface

---

scripts/local-install.sh

Adding a script to the repo since others have found it useful for local development

local-install.sh script for development purposes

---

scripts/local-install.sh

Simple fix to local-install.sh so that it doesn't fail if installing to a target package that doesn't already have the source package as a dependency.
This also removes the need to have `jq` installed in order to use this script.

fix: local-install.sh script only removes dep if it already exists

---

scripts/local-install.sh

---
---
[//]: #  Added 1 line for local-install.sh usage so the person after me won't have to go through the same problems
[//]: # 
[//]: #

Updated instruction for local-install.sh

---

README.md

Address potential issues between `uuid` and `jest`
Add troubleshooting/mitigation steps to readme
N/A

chore: Add troubleshooting section to readme

---

package.json
src/cache/lru-cache.ts
src/client/eppo-client.ts
src/events/default-event-dispatcher.spec.ts
src/events/event-delivery.ts
src/events/event-dispatcher.ts
yarn.lock

This matches our latest iteration on event message format.
As above.
Bump tsc.
Updated tests

chore(events): Update event message format, bump tsc

---

src/index.ts

---
---
It's needed for the signature of `newDefaultEventDispatcher`
N/A
N/A

chore: Export `Event`

---

src/events/sdk-key-decoder.spec.ts
src/events/sdk-key-decoder.ts

As title.
As title.
Updated tests

fix(events): Add event gateway ingestion path to the URL

---

src/events/default-event-dispatcher.spec.ts
src/events/default-event-dispatcher.ts
src/events/event-delivery.ts

---
---
Make sure events generated by the sdk are properly ingested by the event gateway
* Wrap request body array in object with `eppo_events` 
* Include `x-eppo-token` header with SDK key
Updated tests

fix(events): Fix two event ingestion bugs

---

src/client/eppo-client.spec.ts
src/client/eppo-client.ts
src/configuration.ts
src/obfuscation.spec.ts
src/obfuscation.ts

---
---
fixes: #3703
- Simplifies transit format for subject data
- fixes hashing algo bug

fix: salting the hash, subject attributes type

---

package.json

---
---
Goal is to release downstream SDKs using same v4.8.0 of common.
As above
CI

chore: Prepare for v4.8.0 release

---

src/cache/tlru-cache.ts
src/events/batch-event-processor.ts
src/events/event-delivery.ts
src/flag-evaluation-details-builder.ts
src/http-client.ts
src/rules.ts

change created by running `yarn lint:fix`

chore: lint codebase

---

package.json

Updates to 4.12.1 for release.

chore: bump to v4.12.1

---

package.json

---
---
New API: `EppoAssignmentLogger` introduced in #217

chore: Prepare for v4.13.0 release
